name: "OpenSSF Scorecard"

on:
  push:
    branches: ["main"]
  pull_request: {}
  schedule:
    - cron: '0 0 * * 0' # weekly

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  scorecard:
    name: OpenSSF Scorecard Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Harden runner
        uses: step-security/harden-runner@v1

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_format: sarif
          results_file: scorecard.sarif
          publish_results: true

      - name: Upload Scorecard SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scorecard.sarif
